### ISSUE TITLE
Reaching out to screret

### ISSUE THREAD

**Issue by lynnpye** [lynnpye/messagingonly#1]
Hi @screret,

I'm trying to reach you regarding ScreenJS. It's got some issues running against latest KubeJS and hasn't been updated since April.

Do you plan to keep ScreenJS updated? If not, would you mind if I were to work on it and possibly re-release it?

I have a desire to make some custom guis for my modpack and am debating making my own mod for this but would prefer to make use of ScreenJS since it ties nicely into the other KubeJS customization I'm doing.

Thanks,

-Lynn

**Comment by screret** [comment]
Nah, unsupported now, don't have time for it

If you want custom GUIs to that degree you can make a mod or try the KJS painter API.
